# Coinbase API Configuration
coinbase:
  url: https://api.coinbase.com
  readAPIkey: 5gKrLBe4kvmrSNUB
  btcusdpair: /v2/prices/spot?currency_pair=BTC-USD
  btceurpair: /v2/prices/spot?currency_pair=BTC-EUR

## Database Configuration
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase
#    username: myusername
#    password: mypassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
## Logging Configuration
#logging:
#  level:
#    root: INFO
#    com.example: DEBUG
#
## Server Configuration
#server:
#  port: 8080
#
## Custom Application Properties
#custom:
#  property1: value1
#  property2: value2